
matrix:
  include:
    - os: linux
      dist: bionic

language: python

install:
  - pip install -r requirements.txt


script:
  - timeout 30s python manage.py runserver; exit 0
  - pytest  --cov-report term --cov=app/test/
