
matrix:
  include:
    - os: linux
      dist: bionic

language: python

install:
  - pip install -r requirements.txt
  - pip install -r requirements/staging.txt


script:
  - pytest --cov-report term --cov=blog/ --cov=pipeline/ --cov=Mercury/ --cov=seeker/

after_success:
  - codecov
